version: '3.8'

services:
  react:
    build:
      context: ./app/neural-roots-ui
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
