version: '3.8'

services:

  frontend:
    build:
      context: ./src/neural-roots-frontend
      dockerfile: Dockerfile.prod
    volumes:
      - build_file:/usr/src/app/build

  backend:
    build:
      context: ./src/neural-roots-backend
      dockerfile: Dockerfile.prod
    command: gunicorn neural_roots.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - build_file:/usr/share/nginx/html
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - frontend
      - backend

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  build_file:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: