FROM nginxproxy/nginx-proxy
COPY vhost.d/default /etc/nginx/vhost.d/default
COPY custom.conf /etc/nginx/conf.d/custom.conf
COPY frontend.conf /etc/nginx/conf.d/frontend.conf
#COPY web.conf /etc/nginx/conf.d/web.conf
