# Generated by Django 4.2.4 on 2023-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItemModel',
            fields=[
                ('nav_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nav_name', models.CharField(max_length=20)),
                ('is_active', models.BinaryField(max_length=1)),
            ],
        ),
    ]
