# Generated by Django 4.0.3 on 2024-01-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFileModel',
            fields=[
                ('file_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=300)),
                ('is_active', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"public"."candidate_file_tbl"',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='FilMappingeModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=300)),
                ('file_type_id', models.IntegerField()),
                ('is_active', models.BooleanField(max_length=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"public"."candidate_mapping_tbl"',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NavbarItemModel',
            fields=[
                ('nav_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nav_name', models.CharField(max_length=20)),
                ('is_active', models.BinaryField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDataModel',
            fields=[
                ('user_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(max_length=150)),
                ('email_status', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('will_pay', models.BooleanField()),
                ('payment', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('linded_in_profile', models.CharField(blank=True, max_length=500, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('job', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_link', models.CharField(blank=True, max_length=500, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidatefilemodel')),
            ],
            options={
                'db_table': '"public"."candidate_master_data_tbl"',
                'ordering': ['-createdAt'],
            },
        ),
    ]
