# Generated by Django 4.0.3 on 2024-01-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilMappingeModel',
            new_name='FileMappingeModel',
        ),
    ]
