# Generated by Django 4.0.3 on 2024-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_filmappingemodel_filemappingemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefilemodel',
            name='file_status',
            field=models.IntegerField(default=0),
        ),
    ]
