# Generated by Django 5.0.1 on 2024-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidatefilemodel_file_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCountryModel',
            fields=[
                ('country_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"public"."candidate_country_tbl"',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='FileTypeModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(max_length=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"public"."file_type_tbl"',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCategoryModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(max_length=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"public"."program_category_tbl"',
                'ordering': ['-id'],
            },
        ),
    ]
