# Generated by Django 5.0.1 on 2024-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidatecountrymodel_filetypemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypemodel',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='programcategorymodel',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
